# Generated by Django 2.1.4 on 2019-05-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('job', models.CharField(max_length=100)),
                ('upload', models.FileField(upload_to=None)),
            ],
            options={
                'db_table': 'userfield',
            },
        ),
    ]
