# Generated by Django 2.1.4 on 2019-05-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfield',
            old_name='upload',
            new_name='resume',
        ),
    ]
